//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, run by codegen).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in the
// contract assembly: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.
//
// THIS IS NOT A LIST OF EVERY TOPIC ON THE WIRE, and it cannot become one.
// A DYNAMIC namespace is registered at RUNTIME through
// `IUplinkHost.RegisterDynamicNamespace` and materialises its topics per
// subject, so no [SitrepTopic]-tagged type exists for reflection to find and
// nothing about it appears below: `silence.<guid>.*`,
// `currency.<guid>.<currency>`, `vessel.partActions.<flightId>`, and each
// Uplink's own. So a per-subject topic missing from this file may still be
// published: `fleet.<guid>.orbit` is. To enumerate the dynamic half, grep
// the mod for `RegisterDynamicNamespace` instead.
//
// THE PREFIX IS NOT THE TEST, and `fleet.` is the case that proves it.
// `fleet.silence` is statically declared and IS below; `fleet.<guid>.<field>`
// is dynamic and is not. Reading either half as evidence about the other
// goes wrong in both directions.

import type {
  ExampleHeartbeat,
} from "./contract.js";

export interface GeneratedTopicPayloadMap {
  "example.heartbeat": ExampleHeartbeat;
}

export const GENERATED_TOPIC_IDS = [
  "example.heartbeat",
] as const;

// The Topics whose payload is a bare JSON array of the element type, so a
// field path under one names a field of an element and not of the Topic.
// The `[]` above says the same to the type system, and a type is erased.
export const GENERATED_COLLECTION_TOPIC_IDS = [] as const;
