//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/**
 * Every unit token the built-in payloads use.
 *
 * @category Units and values
 */
export type KnownSitrepUnit =
  | "%"
  | "1"
  | "K"
  | "Mit"
  | "W/m²"
  | "bit"
  | "bit/s"
  | "count"
  | "dB"
  | "enum"
  | "f/day"
  | "flag"
  | "funds"
  | "g"
  | "id"
  | "isp"
  | "kN"
  | "kPa"
  | "kW"
  | "kg"
  | "kg/m³"
  | "kg/s"
  | "km"
  | "m"
  | "m/s"
  | "m²"
  | "m³"
  | "m³/s²"
  | "n/a"
  | "rad"
  | "rad/s"
  | "ratio"
  | "rep"
  | "rep/day"
  | "rpm"
  | "s"
  | "science"
  | "science/day"
  | "t"
  | "text"
  | "units"
  | "units/s"
  | "ut"
  | "°"
;

/**
 * A declared unit. OPEN on purpose.
 *
 * The known tokens above still autocomplete. Any other string is accepted
 * too, so an Uplink can declare a unit of its own.
 *
 * A consumer teaches the client what an unknown symbol MEANS by declaring it
 * in UnitDeclarations and calling registerUnit from @ksp-gonogo/sitrep-sdk.
 * Until it does, the value still renders, bare and unscaled.
 *
 * @category Units and values
 */
export type SitrepUnit = KnownSitrepUnit | (string & {});

/**
 * Declared units for one payload shape, keyed by camelCased field name.
 *
 * @category Units and values
 */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "ExampleHeartbeat": {
    ticks: "count",
    ut: "ut",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "example.heartbeat": {
    ticks: "count",
    ut: "ut",
  },
};

/**
 * The nested payload shape each complex field holds, by its interface name.
 *
 * @category Units and values
 */
export type ShapesByField = Readonly<Record<string, string>>;

/**
 * Which fields hold ANOTHER payload shape, and which one.
 *
 * The unit maps above are flat: they describe one shape's own fields and
 * stop there. That was enough while a unit was only ever looked up, and
 * wrong once the runtime started WRAPPING decoded payloads, because a
 * nested shape's declared units were unreachable from the parent's entry.
 * `vessel.target.orbit.sma` is the plain case: the contract types it as
 * Value<"m">, and without this it arrived as a bare number.
 *
 * An entry names the ELEMENT type and says how many of it the field holds:
 * a bare name is one, a leading `*` a string-keyed DICTIONARY of them, and
 * a trailing `[]` a LIST of them. The element is what a consumer indexes
 * into either way, which is the same convention the topic unit map follows
 * for an array Topic.
 *
 * The plural markers are what separate a path something can SAMPLE from a
 * path that only names a field of an element. `contracts.active.agent` is
 * the second kind: `career.status.contracts.active` is an array, so no
 * sample reaches an `agent` under it.
 */
export const GENERATED_TYPE_SHAPES: Readonly<Record<string, ShapesByField>> = {
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_SHAPES: Readonly<Record<string, ShapesByField>> = {
};

/**
 * How each `enum` field reads as a word, keyed by camelCased field name:
 * the enum whose ordinal the wire carries (see GENERATED_ENUM_MEMBERS), or
 * null for a field whose value is already the member's name.
 */
export type EnumsByField = Readonly<Record<string, string | null>>;

/** Keyed by the generated interface name in ./contract.ts. */
export const GENERATED_TYPE_ENUMS: Readonly<Record<string, EnumsByField>> = {
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_ENUMS: Readonly<Record<string, EnumsByField>> = {
};

/**
 * The fields each shape declares [SitrepStatic]: a fact about its subject
 * that does not change with time, so it cannot become stale. Keyed by the
 * generated interface name in ./contract.ts. A field absent here is live.
 *
 * @category Units and values
 */
export const GENERATED_TYPE_STATICS: Readonly<Record<string, readonly string[]>> = {
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_STATICS: Readonly<Record<string, readonly string[]>> = {
};

/**
 * The fields each shape declares [SitrepDeterministicWhile], each against the
 * sibling horizon that gates it: every quantity under the field is exact at
 * any instant while that horizon is Unbounded and Analytic, and stamped so as
 * it is decoded. Keyed by the generated interface name in ./contract.ts.
 *
 * @category Units and values
 */
export const GENERATED_TYPE_DETERMINISTIC_WHILE: Readonly<Record<string, Readonly<Record<string, string>>>> = {
};

/** Each enum an `enum` field names, as its wire value to member name. */
export const GENERATED_ENUM_MEMBERS: Readonly<Record<string, Readonly<Record<number, string>>>> = {
};
